workflow_name: "test_case_01"
jobs:
  - job_id: job_001
    submit_time: 10          # seconds from simulation start
    cpu_cores: 4
    duration: 300            # how long it runs (sec)
    deadline: 600
    license: "synopsys_dc"
  
  - job_id: job_002
    submit_time: 20
    cpu_cores: 2
    duration: 100
    deadline: 200
    license: "cadence_innovus"
